# Generated by Django 5.0.4 on 2024-05-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_direccionenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
