# Generated by Django 5.0.4 on 2024-05-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_orden_precio_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccionenvio',
            name='usuario',
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion_envio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.direccionenvio'),
        ),
    ]
