# Generated by Django 5.0.4 on 2024-05-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_direccionenvio_usuario_orden_direccion_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.producto')),
            ],
        ),
    ]
