# Generated by Django 5.0.4 on 2024-05-15 18:02

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_elementoorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionenvio',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CL'),
        ),
    ]
