# Generated by Django 5.0.4 on 2024-05-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_direccionenvio_correo_direccionenvio_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='elementos',
        ),
        migrations.AddField(
            model_name='orden',
            name='elementos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.elementocarrito'),
        ),
    ]
