# Generated by Django 5.0.4 on 2024-05-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_orden_elementos_orden_elementos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='elementos',
        ),
    ]
