# Generated by Django 5.0.4 on 2024-05-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_orden_elementos'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoorden',
            name='elemento_carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.elementocarrito'),
        ),
        migrations.AddField(
            model_name='orden',
            name='elementos',
            field=models.ManyToManyField(through='blog.ElementoOrden', to='blog.elementocarrito'),
        ),
    ]
